---
- name: RHEL fix for missing dbus-run-session binary
  become: yes
  template:
    src: templates/dbus-run-session.sh.j2
    dest: /usr/local/bin/dbus-run-session
    mode: 0755

- name: read gnome setting for gnome desktop
  become: yes
  become_user: "{{ general.user }}"
  dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    state: read

- name: set global dconf values
  become: yes
  template:
    src: templates/10-local-gtk-settings.j2
    dest: /etc/dconf/db/local.d/10-local-gtk-settings
    mode: 0755

- name: update dconf settings
  become: yes
  command: "dconf update"
