---
- set_fact:
    distro: "{{ansible_os_family}}-{{ansible_distribution_major_version}}"
  tags:
    - vars

- block:
    - include_vars: "{{ item }}"
      with_first_found:
        - "../vars/RedHat-7.yml"
  rescue:
    - fail: msg="Variables file for distro {{ distro }} were not found."
  tags:
    - vars

- name: Install gtk theme deps
  become: true
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - gnome-themes-standard
    - gtk-murrine-engine
    - python-devel
    - python-psutil
  when: ansible_os_family == 'RedHat'

- include: gtk-psutil.yml
  when: ansible_os_family == 'RedHat'

- include: gtk-theme.yml
  when: ansible_os_family == 'RedHat'

- include: gtk-icon.yml
  when: ansible_os_family == 'RedHat'

- include: gtk-extension.yml
  when: ansible_os_family == 'RedHat'

- include: gtk-dconf.yml
  when: ansible_os_family == 'RedHat'
