---
- set_fact:
    distro: "{{ansible_os_family}}-{{ansible_distribution_major_version}}"
  tags:
    - vars

- block:
    - include_vars: "{{ item }}"
      with_first_found:
        - "../vars/{{distro}}.yml"
  rescue:
    - fail: msg="Variables file for distro {{ distro }} were not found."
  tags:
    - vars

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
